### ISSUE TITLE
idea: add current streak like

### ISSUE THREAD

**Issue by RemcoHalman** [RemcoHalman/RemcoHalman#4]
example from : @SashoStoichkov

> https://github.com/SashoStoichkov/SashoStoichkov/tree/ae396eb7602954e99057f49fbfa15fb34d4f1510 

Implementation example
```
---

<p align="center">
  <img width="100%" src="https://github-readme-streak-stats.herokuapp.com/?user=RemcoHalman&show_icons=true&locale=en&layout=demo&theme=merko&hide_border=true" />
</p>

```

---

<p align="center">
  <img width="100%" src="https://github-readme-streak-stats.herokuapp.com/?user=RemcoHalman&show_icons=true&locale=en&layout=demo&theme=merko&hide_border=true" />
</p>

**Comment by SashoStoichkov** [comment]
Here is the link to the profile: https://github.com/SashoStoichkov/SashoStoichkov
